<%-- 
    Document   : index
    Created on : 24-nov-2009, 11:28:37
    Author     : sanpedro
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<%@ page import="java.sql.*" %>  <!importando libraria SQL do JAVA>

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="view.css" media="all">
        <script type="text/javascript" src="view.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database Insert1111 Example</title>
    </head>

    <body>
        <!conteudo HTML para gerar o formulário. gerado automaticamente no site http://www.phpform.org>
        <div id="form_container">
    		<h1><a>Email Contacts</a></h1>
            <form id="form_143578" class="appnitro"  method="post" action="results.jsp">
                <div class="form_description">
                    <h2>Email Contacts</h2>
                    <p></p>
                </div>
                <ul >
                    <li id="li_1" >
                        <label class="description" for="nome">Nome </label>
                        <div>
                            <input id="element_1" name="nome" class="element text medium" type="text" maxlength="255" value=""/>
                        </div>
                    </li>

                    <li id="li_2" >
                        <label class="description" for="sobrenome">Sobrenome </label>
                        <div>
                            <input id="element_2" name="sobrenome" class="element text medium" type="text" maxlength="255" value=""/>
                        </div>
                    </li>

                    <li id="li_3" >
                        <label class="description" for="email">email </label>
                        <div>
                            <input id="element_3" name="email" class="element text medium" type="text" maxlength="255" value=""/>
                        </div>
                    </li>

                    <li id="li_4" >
                        <label class="description" for="sexo">Sexo </label>
                        <span>
                            <input id="element_4_1" name="sexo" class="element radio" type="radio" value="H" />
                            <label class="choice" for="element_4_1">Homem</label>
                            <input id="element_4_2" name="sexo" class="element radio" type="radio" value="M" />
                            <label class="choice" for="element_4_2">Mulher</label>
                        </span>
                    </li>

                    <li class="buttons">
                        <input type="hidden" name="form_id" value="143578" />
                        <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                    </li>
                </ul>
            </form>
            <a href="query.jsp">Show Database Content</a>

            <div id="footer">
                Generated by <a href="http://www.phpform.org">pForm</a>
            </div>
        </div>
    </body>
</html>
